services:
  manager:
    build: ./manager
    working_dir: /manager
    container_name: fine-weather-manager
    environment:
      - FLASK_SQLALCHEMY_DATABASE_URI=sqlite:///data.db
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - IMG_FOLDER_NAME=img
      - THUMBNAIL_FOLDER=thumbnail
      - THUMBNAIL_MAX_WIDTH=600
      - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
    command: /bin/sh -c "flask create-tables --username ${username} --password ${password} && gunicorn -w 4 app:app -b 0.0.0.0:5000"
    volumes:
      - ./manager:/manager
    ports:
      - 20090:5000

  app:
    build: ./app
    container_name: fine-weather
    ports:
      - 80:80
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - manager
